---
- name: Ensure Docker is installed
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

# Only in Debian (Not RaspberryPI)
- name: Ensure AppArmor is installed
  apt:
    name:
      - apparmor
    state: present

- name: Install Docker SDK for Python
  apt:
    name:
      - python3-docker
      - python3-jsondiff
    state: present

- name: Configure Docker daemon to write JSON logs
  copy:
    content: "{{ docker_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: "0644"
  notify: restart docker
  register: docker_config_result

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: yes